In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

iris = load_iris()
X = iris.data#[:, (2, 3)]  # petal length, petal width
y = iris.target#(iris.target == 0).astype(np.int)

per_clf = Perceptron(max_iter=100, tol=-np.infty, random_state=42)
per_clf.fit(X, y)

y_pred = per_clf.predict([[2, 0.5,6,7]])
y_pred

array([2])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = per_clf.predict(X)
print(classification_report(y_pred,y))
print(confusion_matrix(y_pred,y))

              precision    recall  f1-score   support

           0       1.00      0.71      0.83        70
           1       0.58      0.91      0.71        32
           2       0.94      0.98      0.96        48

    accuracy                           0.84       150
   macro avg       0.84      0.87      0.83       150
weighted avg       0.89      0.84      0.85       150

[[50 20  0]
 [ 0 29  3]
 [ 0  1 47]]


In [ ]:
from sklearn.datasets import fetch_openml #fetch_mldata
#mnist=fetch_mldata("MNIST original")
mnist=fetch_openml("mnist_784")
mnist

{'DESCR': "**Author**: Yann LeCun, Corinna Cortes, Christopher J.C. Burges  \n**Source**: [MNIST Website](http://yann.lecun.com/exdb/mnist/) - Date unknown  \n**Please cite**:  \n\nThe MNIST database of handwritten digits with 784 features, raw data available at: http://yann.lecun.com/exdb/mnist/. It can be split in a training set of the first 60,000 examples, and a test set of 10,000 examples  \n\nIt is a subset of a larger set available from NIST. The digits have been size-normalized and centered in a fixed-size image. It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting. The original black and white (bilevel) images from NIST were size normalized to fit in a 20x20 pixel box while preserving their aspect ratio. The resulting images contain grey levels as a result of the anti-aliasing technique used by the normalization algorithm. the images were centered i

In [ ]:
import numpy as np
mnist.target = mnist.target.astype(np.int8) # fetch_openml() returns targets as strings

X, y = mnist["data"], mnist["target"]
X.shape

(70000, 784)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
import numpy as np

from sklearn.linear_model import Perceptron


per_clf = Perceptron(max_iter=100, tol=-np.infty, random_state=42)
per_clf.fit(xtrain, ytrain)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=100, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=42, shuffle=True, tol=-inf,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = per_clf.predict(xtest)
print(classification_report(y_pred,ytest))
print(confusion_matrix(y_pred,ytest))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      1311
           1       0.94      0.97      0.96      1555
           2       0.86      0.90      0.88      1320
           3       0.85      0.90      0.87      1344
           4       0.90      0.86      0.88      1355
           5       0.90      0.73      0.80      1580
           6       0.93      0.94      0.94      1373
           7       0.91      0.91      0.91      1501
           8       0.84      0.72      0.78      1576
           9       0.72      0.94      0.81      1085

    accuracy                           0.88     14000
   macro avg       0.88      0.88      0.88     14000
weighted avg       0.88      0.88      0.88     14000

[[1271    0    4    5    0    4    6   10    7    4]
 [   1 1509   10    6    1    4   10    0   10    4]
 [   4    7 1186   28    8    9   22   32   14   10]
 [   1    8   35 1211   10   33    3    5   22   16]
 [   4    2   25    2 1169   

#MLP
class sklearn.neural_network.MLPClassifier(hidden_layer_sizes=(100), activation='relu', *, solver='adam', alpha=0.0001, batch_size='auto', learning_rate='constant', learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08, n_iter_no_change=10, max_fun=15000)

In [ ]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(random_state=1, max_iter=300).fit(X, y)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [ ]:
y_p=clf.predict(X)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = clf.predict(X)
print(classification_report(y_pred,y))
print(confusion_matrix(y_pred,y))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      1.00      0.97        47
           2       1.00      0.94      0.97        53

    accuracy                           0.98       150
   macro avg       0.98      0.98      0.98       150
weighted avg       0.98      0.98      0.98       150

[[50  0  0]
 [ 0 47  0]
 [ 0  3 50]]
