In [1]:
from sklearn.datasets import fetch_openml 
mnist=fetch_openml("mnist_784")

In [2]:
import numpy as np
mnist.target = mnist.target.astype(np.int8)  
X, y = mnist["data"], mnist["target"]
X.shape

(70000, 784)

In [3]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2, random_state=42)

In [4]:
import numpy as np
from sklearn.linear_model import Perceptron
per_clf = Perceptron(max_iter=100, tol=-np.infty, random_state=42)
per_clf.fit(xtrain, ytrain)

Perceptron(max_iter=100, random_state=42, tol=-inf)

In [5]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = per_clf.predict(xtest)
print(classification_report(y_pred,ytest))
print(confusion_matrix(y_pred,ytest))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      1311
           1       0.94      0.97      0.96      1555
           2       0.86      0.90      0.88      1320
           3       0.85      0.90      0.87      1344
           4       0.90      0.86      0.88      1355
           5       0.90      0.73      0.80      1580
           6       0.93      0.94      0.94      1373
           7       0.91      0.91      0.91      1501
           8       0.84      0.72      0.78      1576
           9       0.72      0.94      0.81      1085

    accuracy                           0.88     14000
   macro avg       0.88      0.88      0.88     14000
weighted avg       0.88      0.88      0.88     14000

[[1271    0    4    5    0    4    6   10    7    4]
 [   1 1509   10    6    1    4   10    0   10    4]
 [   4    7 1186   28    8    9   22   32   14   10]
 [   1    8   35 1211   10   33    3    5   22   16]
 [   4    2   25    2 1169   

In [6]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(random_state=1, max_iter=300).fit(X, y)
y_p=clf.predict(X)

In [7]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = clf.predict(X)
print(classification_report(y_pred,y))
print(confusion_matrix(y_pred,y))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      6870
           1       1.00      1.00      1.00      7860
           2       0.99      0.99      0.99      6998
           3       0.98      0.99      0.99      7068
           4       1.00      1.00      1.00      6832
           5       0.99      0.99      0.99      6290
           6       1.00      1.00      1.00      6891
           7       1.00      0.99      1.00      7312
           8       0.99      0.98      0.99      6915
           9       0.99      0.99      0.99      6964

    accuracy                           0.99     70000
   macro avg       0.99      0.99      0.99     70000
weighted avg       0.99      0.99      0.99     70000

[[6845    0    9    1    0    0    6    1    7    1]
 [   0 7850    0    0    1    0    0    2    7    0]
 [   3    1 6950   28    1    1    5    5    4    0]
 [   0    0    4 7023    0   17    0    0    4   20]
 [   2    4    8    0 6800   