In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b= np.array([[1,2,3],[2,3,4]])
b

array([[1, 2, 3],
       [2, 3, 4]])

In [5]:
a.ndim

1

In [6]:
b.shape

(2, 3)

In [7]:
b.dtype

dtype('int64')

In [8]:
b.itemsize

8

In [9]:
b.size

6

In [10]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
a[:,2]

array([ 3, 10])

In [12]:
a[0,1:6:2]

array([2, 4, 6])

In [16]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b
b.ndim

3

In [17]:
b.shape

(2, 2, 2)

In [18]:
b[1]

array([[5, 6],
       [7, 8]])

In [19]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [29]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [33]:
np.random.random_sample(a.shape)

array([[0.22020206, 0.76874681, 0.74228515, 0.35882153, 0.38859409,
        0.64948038, 0.03905266],
       [0.60298364, 0.57856684, 0.21643455, 0.56627376, 0.69026475,
        0.1392483 , 0.79772359]])

In [36]:
np.random.randint(1,2,size=(10,3))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
test=np.full((5,5),1)
test

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
test[1:4,1:4] = 0
print(test)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [42]:
test[2,2]=9
print(test)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [43]:
test[1:-1,1:-1]

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])